### PR TITLE
Move CI files from libbpf

### PR DESCRIPTION
**Pull request by tsipa**
This also implements clone for CI helpers.

This changes has to be merged first.

### CODE REVIEW

**Review by anakryiko — COMMENTED** [review]
While we are doing this, can we get rid of "travis" terminology and replace it with generic "ci"?

**Review by anakryiko — APPROVED** [review]
Given this blocks other things, I'm approving. But really consider getting rid of confusing travis mentions everywhere as a follow up.

**Comment by tsipa** [comment]
I'd prefer step by step approach.
I will work on bash scripts separately as they concerns me a lot in general - as is it's somewhat hard to manage, but changing them or naming is not the intention of this change.

**Comment by tsipa** [comment]
Only those with write access to this repository can merge pull requests.

**Pull request merged**
